apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-expiration
  template:
    metadata:
      labels:
        app: ticketing-expiration
    spec:
      containers:
        - name: ticketing-expiration
          image: us.gcr.io/celtic-bivouac-308419/expiration
          env:
            - name: NATS_CLUSTER_ID
              value: "ticketing"
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: "ticketing-expiration-redis-srv"
