apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  labels:
    name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: "ticketing.mate"
      http:
        paths:
          - path: "/api/users/?(.*)"
            pathType: Prefix
            backend:
              serviceName: ticketing-auth-srv
              servicePort: 3000
          - path: "/api/tickets/?(.*)"
            pathType: Prefix
            backend:
              serviceName: ticketing-tickets-srv
              servicePort: 3000
          - path: "/?(.*)"
            pathType: Prefix
            backend:
              serviceName: ticketing-client-srv
              servicePort: 3000
